<?php

namespace pocketmine\item;

use pocketmine\block\Block;
use pocketmine\block\VanillaBlocks;

class Campfire extends Item {
	public function getBlock(?int $clickedFace = null) : Block{
		return VanillaBlocks::CAMPFIRE(); // TODO: Change the autogenerated stub
	}
}